apiVersion: v1
kind: Service
metadata:
  name: deso-istio
  namespace: circuit-breaker
  labels:
    app: deso-istio
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: deso-istio