apiVersion: apps/v1
kind: Deployment
metadata:
  name: deso-message-v1
  namespace: deso-istio
spec:
  selector:
    matchLabels:
      app: deso-message
      version: v1
  replicas: 1
  template:
    metadata:
      labels:
        app: deso-message
        version: v1
    spec:
      containers:
      - name: deso-message
        image: r.deso.tech/dsk/deso-message:1.1.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 10
