apiVersion: v1
kind: Service
metadata:
  name: hello-message
  namespace: circuit-breaker
  labels:
    app: hello-message
spec:
  type: NodePort
  ports:
  - port: 8080
    name: http
  selector:
    app: deso-message