apiVersion: v1
kind: Service
metadata:
  name: deso-message
  namespace: deso-istio
  labels:
    app: deso-message
spec:
  type: NodePort
  ports:
  - port: 80
    name: http
  selector:
    app: deso-message